package com.tzh.wallpaperlib.dao.dto;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tzh.wallpaperlib.dao.dto.WidgetDto;

import com.tzh.wallpaperlib.dao.dto.WidgetDtoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig widgetDtoDaoConfig;

    private final WidgetDtoDao widgetDtoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        widgetDtoDaoConfig = daoConfigMap.get(WidgetDtoDao.class).clone();
        widgetDtoDaoConfig.initIdentityScope(type);

        widgetDtoDao = new WidgetDtoDao(widgetDtoDaoConfig, this);

        registerDao(WidgetDto.class, widgetDtoDao);
    }
    
    public void clear() {
        widgetDtoDaoConfig.clearIdentityScope();
    }

    public WidgetDtoDao getWidgetDtoDao() {
        return widgetDtoDao;
    }

}
